# dockerfile

# Use the official Java image
FROM openjdk:17-slim

# Set the working directory
WORKDIR /app

# Define JAR_FILE as an argument.
ARG JAR_FILE=build/libs/*.jar

# Copy the JAR file into the container
COPY ${JAR_FILE} app.jar

# Expose port for the application
EXPOSE 8080

# Start the application
ENTRYPOINT ["java", "-jar", "app.jar"]
